# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chis_sl', '0002_auto_20180323_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O - Positive', 'O - Positive'), ('O - Negative', 'O - Negative'), ('A - Positive', 'A - Positive'), ('A - Negative', 'A - Negative'), ('B - Positive', 'B - Positive'), ('B - Negative', 'B - Negative'), ('AB - Positive', 'AB - Positive'), ('AB - Negative', 'AB - Negative')], db_column='patBGroup', default='O - Positive', max_length=20, null=True, verbose_name='choose blood type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='category',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient')], db_column='patCat', default='Outpatient', max_length=12, verbose_name='select category'),
        ),
    ]
